"""create relationship btn user and event

Revision ID: 4fa6c7ad7862
Revises: 
Create Date: 2020-08-10 12:58:40.481359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa6c7ad7862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
